apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

resources:
  - infrastructure/mysql.yml

components:
  - core/base
  - core/persistence/in-cluster
  - targets/kubernetes/default

bases:
  - plugins/armory-agent

patchesStrategicMerge:
  - persistence/patch-sql-clouddriver.yml
  - core/patches/version.yml
  - plugins/armory-agent/patch-clouddriver.yaml
  - expose/patch-lb.yml