#-----------------------------------------------------------------------------------------------------------------------
# All example patches and configurations are listed here.
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker and all its infrastructure will be installed.
# NOTE: If changed, also change it in all ClusterRoleBinding namespace references.
namespace: ovidiu-dev

resources:
  - spinnakerservice.yml               # (Mandatory). Base spinnaker manifest
#  - infrastructure/opa.yml             # (Optional). OPA server for using with Armory's policy engine, for enforcing pipeline policies
  - accounts/kubernetes/spin-sa.yml    # (Optional, needed by accounts/kubernetes/patch-kube.yml). Kubernetes service account for spinnaker to use in its own cluster


patchesStrategicMerge:
  - persistence/patch-s3.yml


  # Kubernetes accounts
  - accounts/kubernetes/patch-kube.yml


  # Customization to core configuration
  - core_config/patch-timezone.yml                      ## (Optional) adjust the display timezone visible to the user within deck
  - core_config/patch-version.yml                       ## Set the deployed Spinnaker version
  - core_config/patch-deck.yml
  - core_config/patch-gate.yml