apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-custom-config
data:
  halyard-local.yml: |
    secrets:
      vault:
        enabled: true
        url: http://10.100.146.32:8200
        path: kubernetes
        role: dtag
        authMethod: KUBERNETES