apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-07-13T13:48:07Z","generation":1,"name":"spinnaker-operator","namespace":"armory-operator","resourceVersion":"505107304","uid":"9ee0f23f-b42d-4233-8d4a-53879d6f2b94"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"spinnaker-operator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"spinnaker-operator"}},"spec":{"containers":[{"command":["spinnaker-operator"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"spinnaker-operator"},{"name":"DEBUG_ENDPOINT","value":"https://debug.armory.io"}],"image":"armory/armory-operator:1.7.0","imagePullPolicy":"IfNotPresent","name":"spinnaker-operator","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"armory/halyard-armory:1.12.0-7d46af7-operator","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":30,"periodSeconds":20,"successThreshold":1,"tcpSocket":{"port":8064},"timeoutSeconds":1},"name":"halyard","ports":[{"containerPort":8064,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":20,"httpGet":{"path":"/health","port":8064,"scheme":"HTTP"},"initialDelaySeconds":20,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/tmp/tokenFilesecret","name":"foo","readOnly":false}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"spinnaker-operator","serviceAccountName":"spinnaker-operator","terminationGracePeriodSeconds":30,"volumes":[{"name":"foo","secret":{"items":[{"key":"github-token","path":"githubtoken"}],"secretName":"git-token"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-07-13T13:48:38Z","lastUpdateTime":"2022-07-13T13:48:38Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-07-13T13:48:07Z","lastUpdateTime":"2022-07-13T13:48:38Z","message":"ReplicaSet \"spinnaker-operator-7495c69dc4\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-07-13T13:48:07Z"
  generation: 2
  name: spinnaker-operator
  namespace: armory-operator
  resourceVersion: "514571432"
  uid: 9ee0f23f-b42d-4233-8d4a-53879d6f2b94
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: spinnaker-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: spinnaker-operator
    spec:
      containers:
      - command:
        - spinnaker-operator
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: spinnaker-operator
        - name: DEBUG_ENDPOINT
          value: https://debug.armory.io
        image: armory/armory-operator:1.7.0
        imagePullPolicy: IfNotPresent
        name: spinnaker-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /opt/spinnaker/config/halyard.yml
            name: halconfig-volume
            subPath: halyard-local.yml
      - image: armory/halyard-armory:1.12.0-7d46af7-operator
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 8064
          timeoutSeconds: 1
        name: halyard
        ports:
        - containerPort: 8064
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /health
            port: 8064
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/tokenFilesecret
          name: foo
        - mountPath: /opt/spinnaker/config/halyard.yml
          name: halconfig-volume
          subPath: halyard-local.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spinnaker-operator
      serviceAccountName: spinnaker-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: foo
        secret:
          defaultMode: 420
          items:
          - key: github-token
            path: githubtoken
          secretName: git-token
      - name: halconfig-volume
        configMap:
          defaultMode: 420
          name: halyard-custom-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-13T13:48:07Z"
    lastUpdateTime: "2022-07-14T15:45:37Z"
    message: ReplicaSet "spinnaker-operator-8495d77489" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-07-26T23:07:16Z"
    lastUpdateTime: "2022-07-26T23:07:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
