#-----------------------------------------------------------------------------------------------------------------
# Example configuration for adding AWS accounts to spinnaker.
#
# Documentation: https://docs.armory.io/docs/spinnaker-install-admin-guides/add-aws-account/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      providers:
        aws:
          enabled: true
          primaryAccount: christine-aws
          accounts:
          - name: christine-aws
            accountId: '810711266228'
            assumeRole: role/aws-spin-support-managedrole
            providerVersion: V1
            regions:
            - name: us-east-2
            - name: us-east-1
            - name: us-west-1
            - name: us-west-2
            requiredGroupMembership: []
          defaultRegions:
            - name: us-east-1
            - name: us-east-2
            - name: us-west-1
            - name: us-west-2
          defaultKeyPairTemplate: '{{"{{"}}name{{"}}"}}-keypair'
          defaults:
            iamRole: BaseIAMRole
          features:
            cloudFormation:
              enabled: true
        ecs:
          enabled: true
          accounts:
          - name: christine-ecs
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            awsAccount: christine-aws                   # Must be one of the configured AWS accounts
          primaryAccount: christine-ecs            # Must be one of the configured AWS ECS accounts

