apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      spinnaker:
        # These lines are spring-boot configuration to allow access to the metrics
        # endpoints.  This plugin adds the "aop-prometheus" endpoint on the
        # "<service>:<port>/aop-prometheus" path.
        management:
          endpoints:
            web:
              exposure.include: health,info,aop-prometheus
        spinnaker:
          extensibility:
            plugins:
              Armory.ObservabilityPlugin:
                # THIS Is absolutely required, though potentially redundant, otherwise the plugin won't start
                enabled: true
                version: 1.4.1 # 2022-11-01
                # This is the basic configuration for prometheus to be enabled
                config.metrics:
                  # prometheus:
                  #   enabled: true
                  additionalTags:
                    customerName: armory
                    customerEnvName: manuel-local
                  datadog:
                    enabled: true
                    apiKey: encrypted:k8s!n:datadog!k:api-key
                    applicationKey: encrypted:k8s!n:datadog!k:app-key
                    # Optional, Default: https://api.datadoghq.com
                    uri: https://api.datadoghq.com
                    # How often in seconds you want to send metrics to Datadog
                    # Optional, Default: 30
                    stepInSeconds: 30
                    meterRegistryConfig:
                      # By default this plugin adds a set of sane default tags to help with observability best practices, you can disable those here
                      # Optional, Default: false
                      defaultTagsDisabled: false
                      # Configures an opinionated but sane set of default meter filters: https://micrometer.io/docs/concepts#_meter_filters
                      # For example we filter out controller.invocations to prefer the micrometer generated metric 'http.server.requests'
                      # See the following for more details: 
                      # https://github.com/armory-plugins/armory-observability-plugin/blob/master/common/src/main/java/io/armory/plugin/observability/filters/ArmoryRecommendedFilters.java
                      # https://github.com/armory-plugins/armory-observability-plugin/blob/master/common/src/main/java/io/armory/plugin/observability/filters/Filters.java
                      # See bottom of config for controlling percentiles
                      # Optional, Default: false
                      armoryRecommendedFiltersEnabled: true
                  prometheus:
                    enabled: true
                    meterRegistryConfig:
                      armoryRecommendedFiltersEnabled: true #2022-08-22 new added according to https://github.com/armory-plugins/armory-observability-plugin
            repositories:
              armory-observability-plugin-releases:
                url: https://raw.githubusercontent.com/armory-plugins/armory-observability-plugin-releases/master/repositories.json
    service-settings:
      spinnaker:
        kubernetes:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "armory-observability/metrics"
