apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - feature.yml

secretGenerator:
  - name: spin-secrets
    options:
      disableNameSuffixHash: true
    literals:
      - github-token=encrypted:k8s!n:spin-secrets!k:github-toke
