apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker operator will be installed.
# NOTE: If changed, also change it in ClusterRoleBinding namespace references.
namespace: spinnaker-operator

resources:
  - deploy/operator/cluster/role.yaml
  - deploy/operator/cluster/service_account.yaml
  - deploy/operator/cluster/role_binding.yaml
  - deploy/operator/cluster/deployment.yaml

patchesStrategicMerge:
  - patch-config.yaml   # Support for custom operator configuration. Depends on operator-config.

configMapGenerator:
  - name: operator-config
    files:
      - halyard-local.yml
generatorOptions:
  disableNameSuffixHash: true
